import React from 'react';
import styles from '@/styles/Home.module.css'
import Head from 'next/head';

const addPost = () => {
  return (
    <>
      <Head>
        <title>Add Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Add Post
      </main>
    </>
  )
}

export default addPost;